### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by maxholgasson** [hms-networks/AbccSpiAnalyzer#26]
Hi, I'm getting errors when compiling it. How can I fix this?

> $ sudo python build_analyzer.py
Running on Darwin
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccSpiAnalyzerLookup.o" "source/AbccSpiAnalyzerLookup.cpp"
source/AbccSpiAnalyzerLookup.cpp:16:10: fatal error: 'AnalyzerHelpers.h' file not found
#include "AnalyzerHelpers.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccSpiAnalyzerLookup.o" "source/AbccSpiAnalyzerLookup.cpp" -D _DEBUG
source/AbccSpiAnalyzerLookup.cpp:16:10: fatal error: 'AnalyzerHelpers.h' file not found
#include "AnalyzerHelpers.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccSpiAnalyzer.o" "source/AbccSpiAnalyzer.cpp"
In file included from source/AbccSpiAnalyzer.cpp:14:
source/AbccSpiAnalyzer.h:17:10: fatal error: 'Analyzer.h' file not found
#include "Analyzer.h"
         ^~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccSpiAnalyzer.o" "source/AbccSpiAnalyzer.cpp" -D _DEBUG
In file included from source/AbccSpiAnalyzer.cpp:14:
source/AbccSpiAnalyzer.h:17:10: fatal error: 'Analyzer.h' file not found
#include "Analyzer.h"
         ^~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccSpiSimulationDataGenerator.o" "source/AbccSpiSimulationDataGenerator.cpp"
In file included from source/AbccSpiSimulationDataGenerator.cpp:16:
source/AbccSpiSimulationDataGenerator.h:15:10: fatal error: 'AnalyzerHelpers.h' file not found
#include <AnalyzerHelpers.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccSpiSimulationDataGenerator.o" "source/AbccSpiSimulationDataGenerator.cpp" -D _DEBUG
In file included from source/AbccSpiSimulationDataGenerator.cpp:16:
source/AbccSpiSimulationDataGenerator.h:15:10: fatal error: 'AnalyzerHelpers.h' file not found
#include <AnalyzerHelpers.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccCrc.o" "source/AbccCrc.cpp"
source/AbccCrc.cpp:12:10: fatal error: 'Analyzer.h' file not found
#include "Analyzer.h"
         ^~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccCrc.o" "source/AbccCrc.cpp" -D _DEBUG
source/AbccCrc.cpp:12:10: fatal error: 'Analyzer.h' file not found
#include "Analyzer.h"
         ^~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccSpiAnalyzerSettings.o" "source/AbccSpiAnalyzerSettings.cpp"
In file included from source/AbccSpiAnalyzerSettings.cpp:23:
source/AbccSpiAnalyzerSettings.h:15:10: fatal error: 'AnalyzerSettings.h' file not found
#include <AnalyzerSettings.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccSpiAnalyzerSettings.o" "source/AbccSpiAnalyzerSettings.cpp" -D _DEBUG
In file included from source/AbccSpiAnalyzerSettings.cpp:23:
source/AbccSpiAnalyzerSettings.h:15:10: fatal error: 'AnalyzerSettings.h' file not found
#include <AnalyzerSettings.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/release/include" -O3 -w -c -fpic -std=c++11 -o "./plugins/OSX/AbccSpiAnalyzerResults.o" "source/AbccSpiAnalyzerResults.cpp"
In file included from source/AbccSpiAnalyzerResults.cpp:17:
source/AbccSpiAnalyzerResults.h:15:10: fatal error: 'AnalyzerResults.h' file not found
#include "AnalyzerResults.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -I"./sdk/debug/include" -O0 -w -c -fpic -g -std=c++11 -m32 -o "./plugins/OSX/Debug/AbccSpiAnalyzerResults.o" "source/AbccSpiAnalyzerResults.cpp" -D _DEBUG
In file included from source/AbccSpiAnalyzerResults.cpp:17:
source/AbccSpiAnalyzerResults.h:15:10: fatal error: 'AnalyzerResults.h' file not found
#include "AnalyzerResults.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
g++ -L"./sdk/release/lib" -lAnalyzer -dynamiclib -o "./plugins/OSX/libAbccSpiAnalyzer.dylib" "./plugins/OSX/AbccSpiAnalyzerLookup.o" "./plugins/OSX/AbccSpiAnalyzer.o" "./plugins/OSX/AbccSpiSimulationDataGenerator.o" "./plugins/OSX/AbccCrc.o" "./plugins/OSX/AbccSpiAnalyzerSettings.o" "./plugins/OSX/AbccSpiAnalyzerResults.o" 
clang: error: no such file or directory: './plugins/OSX/AbccSpiAnalyzerLookup.o'
clang: error: no such file or directory: './plugins/OSX/AbccSpiAnalyzer.o'
clang: error: no such file or directory: './plugins/OSX/AbccSpiSimulationDataGenerator.o'
clang: error: no such file or directory: './plugins/OSX/AbccCrc.o'
clang: error: no such file or directory: './plugins/OSX/AbccSpiAnalyzerSettings.o'
clang: error: no such file or directory: './plugins/OSX/AbccSpiAnalyzerResults.o'
g++ -L"./sdk/debug/lib" -lAnalyzer -dynamiclib -m32 -o "./plugins/OSX/Debug/libAbccSpiAnalyzer.dylib" "./plugins/OSX/Debug/AbccSpiAnalyzerLookup.o" "./plugins/OSX/Debug/AbccSpiAnalyzer.o" "./plugins/OSX/Debug/AbccSpiSimulationDataGenerator.o" "./plugins/OSX/Debug/AbccCrc.o" "./plugins/OSX/Debug/AbccSpiAnalyzerSettings.o" "./plugins/OSX/Debug/AbccSpiAnalyzerResults.o" 
clang: error: no such file or directory: './plugins/OSX/Debug/AbccSpiAnalyzerLookup.o'
clang: error: no such file or directory: './plugins/OSX/Debug/AbccSpiAnalyzer.o'
clang: error: no such file or directory: './plugins/OSX/Debug/AbccSpiSimulationDataGenerator.o'
clang: error: no such file or directory: './plugins/OSX/Debug/AbccCrc.o'
clang: error: no such file or directory: './plugins/OSX/Debug/AbccSpiAnalyzerSettings.o'
clang: error: no such file or directory: './plugins/OSX/Debug/AbccSpiAnalyzerResults.o'

**Comment by joca-hms** [comment]
Did you run the following which was mentioned in the README?
I verified the build is working fine here.

```
git submodule update --init --recursive
```

**Comment by maxholgasson** [comment]
Hi,

yes but I'm not 100% sure if I followed correctly. 
>git submodule update --init --recursive

outputs
>fatal: not a git repository (or any of the parent directories): .git

In the meanwhile I read that there is a SDK available from Saleae. Do I need to install this first in order to install your plugin?

**Comment by maxholgasson** [comment]
I found that you have a compiled version to download
https://github.com/hms-networks/AbccSpiAnalyzer/releases

This one worked. It wasn't clear in the description. Maybe you can add that downloadlink or make it more clear that it's not a must to compile it by yourself.
Thanks for the plugin!

**Comment by joca-hms** [comment]
> In the meanwhile I read that there is a SDK available from Saleae. Do I need to install this first in order to install your plugin?

For reference, in order to use the git submodule command you must first have a valid git repository. From the error you mention it seems you only downloaded the repo as a zip. When downloading as a zip, GitHub omits the git-repository (i.e. the .git folder).

I will consider expanding on the setup instructions to avoid this in case there is unfamiliarity with with git-submodules.

Example:

```
git clone https://github.com/hms-networks/AbccSpiAnalyzer.git
cd AbccSpiAnalyzer
git submodule update --init --recursive
```

> Maybe you can add that downloadlink or make it more clear that it's not a must to compile it by yourself.

I do mention it in the "Compile & Install" section, but I will consider improving this to making it more noticeable. Maybe even adding a link to the releases page:

> While tagged releases are provided which contain precompiled libraries and associated documentation, you may still opt to compile the libraries yourself.

Thanks for your feedback.
