### ISSUE TITLE
Not correct interpretation of the command.

### ISSUE THREAD

**Issue by brunjak** [hms-networks/AbccSpiAnalyzer#27]
The interpretation of the command of the MISO frame shows 0x11. However, the data is 0x51.

![misoCmd](https://user-images.githubusercontent.com/8336591/103311769-7d330480-4a1b-11eb-8a12-5d67d668d577.PNG)

**Comment by joca-hms** [comment]
Admittedly this can be a little confusing, but nothing is wrong here. This field will be presented in two forms: "CMD" or "RSP". The presence of bit 7 in this field indicates that the packet contains a command and thus the bit is removed from the raw payload to give you the raw command, which is results in the value going from 0x51-->0x11.

**Comment by joca-hms** [comment]
It is worth noting that the plugin has fallen a little behind on the lookup table entries, so if you are wondering why 0x11 is not resolving to a known command, this is why. I will be releasing a new version soon which will address this.

**Comment by brunjak** [comment]
Thank you.

Your tool helped a lot ;-).

Jakob

Am Di., 5. Jan. 2021 um 15:10 Uhr schrieb Jon Carrier <
notifications@github.com>:
